// Builds a local review page of every avatar in public/people/ at exactly the
// two sizes the site renders them (112 px testimonial circle on the #4A7A9B
// band, 136 px team-ticker circle on the #1A3A5C band) so the user can approve
// crops before anything is committed. Output is gitignored.
//
// Run: node scripts/people-sheet.mjs
//      python3 -m http.server 8899 --directory .contact-sheet/people
import { copyFile, mkdir, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const src = path.join(root, 'public', 'people')
const outDir = path.join(root, '.contact-sheet', 'people')
const imgDir = path.join(outDir, 'img')

await mkdir(imgDir, { recursive: true })

const files = (await readdir(src)).filter((f) => /\.webp$/i.test(f)).sort()
for (const f of files) await copyFile(path.join(src, f), path.join(imgDir, f))

const card = (f, size, bg) => `
  <figure style="background:${bg}">
    <img src="img/${f}" width="${size}" height="${size}" alt="${f}" style="width:${size}px;height:${size}px">
    <figcaption>${path.parse(f).name} · ${size}px</figcaption>
  </figure>`

const html = `<!doctype html><meta charset="utf-8"><title>UBCPSS avatars — ${files.length} files</title>
<style>
  body { font: 15px/1.5 -apple-system, system-ui, sans-serif; background:#F4F8FC; color:#0F1E2E; margin:0; padding:32px }
  h1 { font-size:26px; margin:0 0 6px } p.lede { margin:0 0 24px; color:#2E5070; max-width:70ch }
  b.warn { color:#c0392b }
  h2 { font-size:16px; margin:28px 0 12px; color:#2E5070 }
  .grid { display:flex; flex-wrap:wrap; gap:14px }
  figure { margin:0; border-radius:18px; padding:16px 14px 10px; text-align:center; min-width:150px }
  img { display:block; margin:0 auto; border-radius:50%; object-fit:cover; border:2px solid rgba(255,255,255,.35); background:rgba(255,255,255,.12) }
  figcaption { color:#fff; font-size:12px; margin-top:8px; font-weight:600 }
</style>
<h1>Avatar review — ${files.length} files</h1>
<p class="lede"><b class="warn">Approve before commit. Catherina must NOT appear.</b> Each avatar is shown at exactly the two sizes the site uses. Check that every face is whole and centred, and that no rings, dots, lines or purple slivers show inside the circle.</p>
<h2>Testimonial cards · 112 px on #4A7A9B</h2>
<div class="grid">${files.map((f) => card(f, 112, '#4A7A9B')).join('')}</div>
<h2>Team ticker · 136 px on #1A3A5C</h2>
<div class="grid">${files.map((f) => card(f, 136, '#1A3A5C')).join('')}</div>
<p class="lede" style="margin-top:28px">Generated by scripts/people-sheet.mjs from public/people/. Names: ${files.map((f) => path.parse(f).name).join(', ')}.</p>`

await writeFile(path.join(outDir, 'index.html'), html)
console.log(`${files.length} avatars → ${path.join(outDir, 'index.html')}`)
